name: sigob_imoveis
version: 1.0.0
config-version: 2
profile: sigob_imoveis

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  sigob_imoveis:
    silver:
      +schema: silver
      +materialized: external
      +format: parquet
    intermediate:
      +schema: intermediate
      +materialized: view
    gold:
      +schema: gold
      +materialized: external
      +format: parquet

flags:
  require_generic_test_arguments_property: true
